# Generated by Django 6.0.3 on 2026-08-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(help_text='Per unit price (Per Kg for kg/gm)'),
        ),
    ]
