# Generated by Django 6.0.3 on 2026-08-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_id',
            field=models.IntegerField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
