# Generated by Django 5.1.15 on 2026-08-22 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
