# Generated by Django 6.0.3 on 2026-08-07 14:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_paymentreceipt_customer_and_more'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'verbose_name_plural': 'Expense Categories'},
        ),
        migrations.RemoveField(
            model_name='expense',
            name='account',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='bkash_charge',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='grand_total',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='packaging_charge',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='paymentreceipt',
            name='customer',
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_account',
            field=models.ForeignKey(blank=True, help_text='Expense Ledger Account', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_entries', to='finance.account'),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_account',
            field=models.ForeignKey(blank=True, help_text='Cash or Bank Account used to pay expense', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_payments', to='finance.account'),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='party_account',
            field=models.ForeignKey(blank=True, help_text='Customer or Supplier Account', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='party_payments', to='finance.account'),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='payment_account',
            field=models.ForeignKey(blank=True, help_text='Cash or Bank Account', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_bank_payments', to='finance.account'),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='payment_type',
            field=models.CharField(choices=[('receipt', 'Receive Payment (Customer)'), ('payment', 'Make Payment (Supplier/Liability)')], default='receipt', max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='account',
            name='expense_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to='finance.expensecategory'),
        ),
        migrations.AlterField(
            model_name='account',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to='products.product'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='expense',
            name='journal',
            field=models.OneToOneField(blank=True, help_text='Auto-linked accounting journal voucher', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_record', to='finance.journal'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_journals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='journal',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_journals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='journal',
            name='journal_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='journal',
            name='reference_type',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('purchase', 'Purchase'), ('payment', 'Payment'), ('receipt', 'Receipt'), ('expense', 'Expense'), ('journal', 'Journal'), ('contra', 'Contra'), ('manual', 'Manual')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='journal',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], default='posted', max_length=20),
        ),
        migrations.AlterField(
            model_name='journal',
            name='voucher_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='voucher_type',
            field=models.CharField(choices=[('sales', 'Sales Voucher'), ('purchase', 'Purchase Voucher'), ('payment', 'Payment Voucher'), ('receipt', 'Receipt Voucher'), ('expense', 'Expense Voucher'), ('journal', 'Journal Voucher'), ('contra', 'Contra Voucher')], default='journal', max_length=20),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='voucher_type',
            field=models.CharField(blank=True, choices=[('sales', 'Sales Voucher'), ('purchase', 'Purchase Voucher'), ('payment', 'Payment Voucher'), ('receipt', 'Receipt Voucher'), ('expense', 'Expense Voucher'), ('journal', 'Journal Voucher'), ('contra', 'Contra Voucher')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='journal',
            field=models.OneToOneField(blank=True, help_text='Auto-linked accounting journal voucher', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_record', to='finance.journal'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='received_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
