# Generated by Django 6.0.3 on 2026-08-07 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_expensecategory_options_remove_expense_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentreceipt',
            name='journal',
            field=models.ForeignKey(blank=True, help_text='Related Journal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_records', to='finance.journal'),
        ),
    ]
