# Generated by Django 6.0.3 on 2026-08-07 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_paymentreceipt_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_records', to='finance.journal'),
        ),
    ]
