# Generated by Django 6.0.3 on 2026-08-07 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_expense_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='journal',
            field=models.OneToOneField(blank=True, help_text='Auto-linked accounting journal voucher', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_record', to='finance.journal'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='journal',
            field=models.OneToOneField(blank=True, help_text='Auto-linked accounting journal voucher', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_record', to='finance.journal'),
        ),
    ]
