# Generated by Django 6.0.3 on 2026-08-09 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_alter_expense_journal_alter_paymentreceipt_journal'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherPaymentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(help_text='Customer or Supplier account', on_delete=django.db.models.deletion.CASCADE, related_name='voucher_payment_lines', to='finance.account')),
                ('payment_journal', models.ForeignKey(help_text='The Payment/Receipt Journal (RV/PV)', on_delete=django.db.models.deletion.CASCADE, related_name='settlement_lines', to='finance.journal')),
                ('reference_voucher', models.ForeignKey(help_text='The original Sales/Purchase/Expense/Journal voucher being settled', on_delete=django.db.models.deletion.CASCADE, related_name='payment_settlements', to='finance.journal')),
            ],
            options={
                'verbose_name': 'Voucher Payment Line',
                'verbose_name_plural': 'Voucher Payment Lines',
                'ordering': ['-created_at'],
            },
        ),
    ]
