# Generated by Django 6.0.3 on 2026-08-12 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_alter_voucherpaymentline_reference_voucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucherpaymentline',
            name='reference_voucher',
            field=models.ForeignKey(blank=True, help_text='The original Sales/Purchase/Expense/Journal voucher being settled (null if Opening Balance)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_settlements', to='finance.journal'),
        ),
    ]
