# Generated by Django 6.1 on 2026-08-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_alter_voucherpaymentline_reference_voucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type2',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('customer', 'Customer'), ('supplier', 'Supplier'), ('receivable', 'Receivable'), ('payable', 'Payable'), ('product', 'Product'), ('capital', 'Capital'), ('purchase', 'Purchase'), ('discount', 'Discount'), ('packaging', 'Packaging Charge'), ('bkash_charge', 'bKash Charge'), ('bad_debt', 'Bad Debt / Expected Credit Loss'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
